name: Run
on:
  workflow_dispatch:
jobs:
  run:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x
      - name: publish
        run: |
          dotnet publish Console/Console.csproj -f net8.0
          dotnet publish Console/Console.csproj -f net9.0
      - name: Run
        shell: bash
        run: |
         echo '# ${{matrix.os}}' >> $GITHUB_STEP_SUMMARY
         echo '## Default(.NET8) on ${{matrix.os}}' >> $GITHUB_STEP_SUMMARY
         dotnet Console/bin/Release/net8.0/*/Console.dll >> $GITHUB_STEP_SUMMARY
         echo '## Default(.NET9) on ${{matrix.os}}' >> $GITHUB_STEP_SUMMARY
         dotnet Console/bin/Release/net9.0/*/Console.dll >> $GITHUB_STEP_SUMMARY
         echo '## NativeAOT(.NET8) on ${{matrix.os}}' >> $GITHUB_STEP_SUMMARY
         Console/bin/Release/net8.0/*/publish/Console >> $GITHUB_STEP_SUMMARY
         echo '## NativeAOT(.NET9) on ${{matrix.os}}' >> $GITHUB_STEP_SUMMARY
         Console/bin/Release/net9.0/*/publish/Console >> $GITHUB_STEP_SUMMARY
